version: "3"
services:
  postgress:
    image: postgres:10.4-alpine
    networks: 
      - lognet
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
    networks: 
      - lognet
networks:
  lognet:
    driver: bridge
