version: "2"
services:
  postgres:
    build:
      dockerfile: Dockerfile
      context: './'
    environment:
        - POSTGRES_PASSWORD=123
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
    networks: 
      - lognet
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    volumes:
      - ./jenkinsFiles:/var/jenkins_home
    networks: 
      - lognet
networks:
  lognet:
    driver: bridge
