CREATE DATABASE dev;
CREATE USER dev WITH PASSWORD 'dev';
GRANT ALL PRIVILEGES ON DATABASE dev TO dev;

CREATE DATABASE staging;
CREATE USER staging WITH PASSWORD 'staging';
GRANT ALL PRIVILEGES ON DATABASE staging TO staging;
